name: doctor
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_gemini: ^3.0.0
  dash_chat_2: ^0.0.21
  animated_background: ^2.0.0
  image: ^3.0.1
  tflite_flutter: ^0.11.0
  camera: ^0.11.0


  
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lung.jpg
    - assets/hhh.jpg
    - assets/PN.tflite
    - assets/start1.jpg
    - assets/home1.jpg
    - assets/homedd.jpg
